### ISSUE TITLE
instalador: revisar acción botones ok, cancel y close

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#13]
En el instalador, revisar las acciones que tienen los botones ok y cancel, al igual que la cruz de cerrar ventana. Revisarlo en todas las etapas de la instalación.
Ejemplo: puse cancelar antes de dar ok, no tuvo acción el botón, y al dar clic en 'ok' solo copió el primer archivo. Cerré el instalador. Lo ejecuté de nuevo, di clic en 'ok', e instaló correctamente.

**Comment by jsbarbosa** [comment]
Lo anterior debe estar resuelto en la versión de 12 de Junio, 2017 del instalador. 

Sin embargo el issue permanece abierto en tanto no se pruebe estabilidad y portabilidad.

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.1.0
