### ISSUE TITLE
sugerencia nombre y ruta archivo por defecto

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#14]
Sugiero que la ruta del archivo de datos por defecto sea:
1) carpeta 'mis documentos/tausandData'
2) que el nombre del archivo sea 'dataSessionDateTime.dat'. Ejemplo: 'dataSession20170607_1050.dat'
Donde DateTime sea aquella del momento de inicio del programa.

Esto evitará que la acción de escritura por defecto sea 'append', y hará más probable que la acción sea crear nuevo archivo de datos.

**Comment by jsbarbosa** [comment]
La sugerencia se encuentra implementada en la versión de 11 de Junio, 2017. Se agregó en la ventana de valores por defecto un checkbox para mediar el comportamiento entre el prefijo del nombre y la estampilla del tiempo. 

La sugerencia 1 aún no se encuentra implementada.

**Comment by jsbarbosa** [comment]
El problema de 'efectividad' de la sugerencia 2 ahora está resuelto.

**Comment by daguzman35** [comment]
En versión 1.1.3b
La ruta por defecto es: 'C:/Users/David/Documents/' (correcto)
![imagen](https://user-images.githubusercontent.com/14864395/35536304-821a90a2-0514-11e8-8a97-edac13b319e8.png)

Al hacer clic en el botón 'open', se abre una ventana que sugiere que se guarde por defecto en 'C:/Users/David/' (incorrecto).
![imagen](https://user-images.githubusercontent.com/14864395/35536340-945a0874-0514-11e8-80f9-624526748dac.png)

**Comment by jsbarbosa** [comment]
Corregido en versión 1.1.4
