### ISSUE TITLE
tiempos de muestreo, limitarlos

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#23]
Solicito cambiar los tiempos de muestreo válidos (sampling) a solo los siguientes:
1ms, 2ms, 5ms, 10ms, 20ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s, 10s, 20s, 50s, 100s, 200s, 500s, 1000s.

Puede ser con un desplegable.

No permitir valores arbitrarios como está actualmente.

**Comment by jsbarbosa** [comment]
El cambio se encuentra implementado, sin embargo hacen falta pruebas.

**Comment by daguzman35** [comment]
El texto tanto de 'global properties' como de 'default properties' dice actualmente 'Sampling (ms)'. Ahora con el desplegable debemos quitar los caracteres '(ms)' de estas etiquetas.

**Comment by jsbarbosa** [comment]
Incluido en la versión 1.0.2
