### ISSUE TITLE
no ejecuta versión del 20 de septiembre

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#24]
He instalado la versión del 20 de septiembre de 2017. Al ejecutarla, aparece el logo inicial junto con una terminal, empieza a cargar, y aproximadamente en el 40% se cierra.
Alcanzo a capturar pantalla con los siguientes mensajes de error en la terminal
![pantalla error al iniciar](https://user-images.githubusercontent.com/14864395/30784591-9f179516-a11d-11e7-91e5-72a0595c9b0e.png)
Noto además que el archivo "params.txt" alcanza a ser creado en el escritorio, con el siguiente contenido:

```
##### PARAMETERS USED #####
Reimagined Quantum session began at Sun Sep 24 11:39:20 2017
```

**Comment by jsbarbosa** [comment]
Se debe borrar el archivo default.py de las versiones anteriores. El issue es entonces con el desinstalador que no lo hace.

**Comment by daguzman35** [comment]
Gracias. Tras borrar el arhivo default.py de versión anterior, se ejecuta correctamente el programa.
