### ISSUE TITLE
menú superior, desplegar hacia abajo

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#26]
El menú superior se está desplegando hacia arriba. Cambiarlo a que siempre se despliegue hacia abajo.
![menu_arriba](https://user-images.githubusercontent.com/14864395/31317539-6757efe0-ac08-11e7-97ee-5589e7d8eff2.png)

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.1.0
