### ISSUE TITLE
desinstalador

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#28]
En 'abacus software', v1.0.01, al intentar desinstalar el programa entrega un mensaje de error; dice que se necesita ser administrador. En anteriores versiones no se presentaba este requerimiento.
![desinstalando](https://user-images.githubusercontent.com/14864395/31317640-3a68829a-ac0a-11e7-8715-13cf41dcf49b.png)

**Comment by jsbarbosa** [comment]
Esto siempre ha ocurrido, no es nuevo de la versión. Así como para instalar se requiere ser administrador para desintalar también.
