### ISSUE TITLE
relación de aspecto ícono

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#29]
En menú superior del software y en las ventanas emergentes, el icono de Tausand aparece estirado horizontalmente sin mantener relación de aspecto original.
![iconos_en_software](https://user-images.githubusercontent.com/14864395/31317738-ea53387a-ac0b-11e7-8490-c8c38f23e750.png)

En el icono de escritorio y aquel de barra de programas, el icono sí tiene la relación correcta.

![icono_escritorio](https://user-images.githubusercontent.com/14864395/31317742-edca63ac-ac0b-11e7-8fbc-0237d30246bd.PNG)

![icono_inferiorescritorio](https://user-images.githubusercontent.com/14864395/31317743-f4684454-ac0b-11e7-9cb0-06155e12738a.PNG)

Adjunto imagen de 32x32pixeles con la relación de aspecto correcta.
![tausand_prop6_icon_fromai](https://user-images.githubusercontent.com/14864395/31317721-b1c5cf2c-ac0b-11e7-93e7-3eff09319877.png)

**Comment by jsbarbosa** [comment]
Solucionado con el cambio de imagen.
