### ISSUE TITLE
sampling time 1s no reconocido

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#31]
Al leer los parámetros del dispositivo (hardware), el software muestra un espacio en blanco en el campo 'sampling time' únicamente cuando ese valor es 1s. Para los demás valores (500ms, 2s, etc) muestra el valor correctamente. Ejemplo:
![imagen](https://user-images.githubusercontent.com/14864395/35536807-f03729a0-0515-11e8-8a9a-bc75a9c02345.png)
En la terminal se lee el siguiente mensaje: "Sampling Value,0"
![imagen](https://user-images.githubusercontent.com/14864395/35536838-101557f6-0516-11e8-9888-ef3699610f42.png)

Si se configura el parámetro por software, hardware lo ve correctamente cómo 1s.

Al hacer el mismo ejercicio en LabView, se puede ver que el registro 18 (samplingTime_ms) tiene guardado un 0, que el registro 19 (samplingTime_s) tiene guardado un 1, y el registro 20 (coinwin_ns) tiene un 10. A continuación pantallazo de LabView:
![imagen](https://user-images.githubusercontent.com/14864395/35537010-b38838cc-0516-11e8-9d6d-e59258f13eb7.png)

(versión 1.1.3b)

**Comment by jsbarbosa** [comment]
Corregido en versión 1.1.4
