### ISSUE TITLE
cierre inesperado al reconectar dispositivo

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#32]
Encontré el siguiente escenario que cierra completamente el software, sin lanzar mensaje de error. Se cierra inclusive la ventana de la terminal.

Los pasos son:

- Conectar dispositivo usando botón 'connect'
- Iniciar adquisición usando botón 'start acquisition'
- Apago el dispositivo durante adquisición. Aquí el software identifica un error en comunicación y entrega el mensaje de error (correcto).
- Enciendo de nuevo el dispositivo.
- Conectar dispositivo usando botón 'connect'.
- Iniciar adquisición usando botón 'start acquisition'. Justo al dar clic en este botón, el programa se cierra abruptamente.

Lo hice 2 veces, y ambas presentó el mismo resultado.

(versión 1.1.3b)

**Comment by jsbarbosa** [comment]
Corregido en versión 1.1.4
