### ISSUE TITLE
eje vertical gráfica muy pequeño

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#33]
La altura y tamaño de la ventana es correcto. Sin embargo el tamaño del eje vertical de las gráficas considero es demasiado pequeño. Hay unos espacios vacíos abajo y arriba de las gráficas que se podrían aprovechar, lo mismo que un espacio arriba y abajo de la entrada de 'save as'. Adjunto un pantallazo de cómo se ve el software de Python (izquierda) y el software de LabView (derecha).
![2018-01-29 abacus 1 1 3 pantallazo 4](https://user-images.githubusercontent.com/14864395/35537634-edfe14de-0518-11e8-8b4a-abc517d1f639.png)

(versión 1.1.3b)

**Comment by jsbarbosa** [comment]
Corregido en versión 1.1.4
