### ISSUE TITLE
alinear números a la derecha

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#34]
Alinear todos los números a la derecha donde sea posible. Ejemplo: settings
![imagen](https://user-images.githubusercontent.com/14864395/35537912-001e20ea-051a-11e8-90fc-adcf5671ec36.png)
inclusive el campo 'sampling time'.
En pestaña 'historical data' ya están a la derecha (ok).

(versión 1.1.3b)

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.2.4
