### ISSUE TITLE
cierre inesperado al cambiar ruta archivo

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#35]
Encontré el siguiente escenario que cierra completamente el software, sin lanzar mensaje de error.

Los pasos son:
- Dar clic en botón 'open' para cambiar ruta de archivo
- Escoger nueva ruta y aceptar

Otro escenario con mismo resultado:
- Dar clic en menú 'File/Save as..."
- Escoger nueva ruta y aceptar

También lo hice durante una adquisición de datos, e igualmente se cierra el software sin dar aviso.
(versión 1.1.4)

**Comment by jsbarbosa** [comment]
Corregido en versión 1.1.5
