### ISSUE TITLE
ubicación ventana

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#36]
Al abrir el software, el borde superior de la ventana está fuera de la pantalla, lo que impide minimizar o cerrar el programa con los íconos usuales.
Adjunto pantallazo:
![pantallazo abacus1 2 0](https://user-images.githubusercontent.com/14864395/38471491-485d6af2-3b37-11e8-97d6-3f17461e0cee.png)

Sistema operativo: windows 10
Versión software: 1.2.3

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.2.4
