### ISSUE TITLE
dígitos en ventana current

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#37]
Revisar el número de dígitos visibles en la ventana 'current' tan pronto se inicia el programa.

Hice una prueba con 60 millones (8 dígitos), y el octavo dígito aparece recortado.
![pantallazo abacus1 2 3 current](https://user-images.githubusercontent.com/14864395/38471524-10450ebc-3b38-11e8-98d8-781858835cdc.png)

Si se maximiza y se vuelve a restaurar la ventana 'current', el número aparece correcto, sin recortar.
![pantallazo abacus1 2 3 current 2](https://user-images.githubusercontent.com/14864395/38471544-51eb43e0-3b38-11e8-9772-8d38616ed3ce.png)

Si se cambia el tamaño de la ventana manualmente, también aparece correcto.
![pantallazo abacus1 2 3 current 3](https://user-images.githubusercontent.com/14864395/38471574-9a89263a-3b38-11e8-82c7-d6cc61bc9fc6.png)

Versión software: 1.2.3

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.2.4
