### ISSUE TITLE
'fatal error' cuando no hay conexión a Internet

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#38]
Cuando no hay conexión a Internet disponible, el software al iniciar muestra la imagen de inicio, y entrega el siguiente mensaje de error:

> Fatal Error!
Failed to execute script main

Al dar 'aceptar', el software se cierra. Adjunto pantallazo:
![sin internet fatal error abacus 1 2 4](https://user-images.githubusercontent.com/14864395/40930709-0ed9e68c-67ee-11e8-9901-2cd07ffe3a2b.png)

(versión 1.2.4)

**Comment by jsbarbosa** [comment]
Corregido en la version 1.2.5
