### ISSUE TITLE
menú 'save as': cargar valor actual como inicial

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#39]
En los diferentes menús de 'save as', al hacer clic se carga una ventana para seleccionar la ruta, pero cuyo nombre de archivo inicialmente es vacío. Cambiar esto para que asigne por defecto la ruta y nombre del archivo que está asignado actualmente.

Esto facilita la edición de nombres de archivo y rutas.

![editar saveas](https://user-images.githubusercontent.com/14864395/40931893-54329144-67f2-11e8-8d77-fede92d4a48c.png)

(versión 1.2.4)

**Comment by jsbarbosa** [comment]
Resuelto en la versión 1.3.2
