### ISSUE TITLE
barrido: revisión límites

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#40]
En los aplicativos de barridos, hay los siguientes problemas con las restricciones de valores:

1.  El usuario puede ingresar por teclado valores fuera de los permitidos. Ejemplo: delay: start time = -11ns.
![barridos restringir valores por teclado](https://user-images.githubusercontent.com/14864395/40932152-fda60382-67f2-11e8-828c-98017249347d.png)

2.  Limitar los valores del barrido respetando los límites dados por el usuario. Ejemplo: el usuario ingresa inicial 50ns, final 95ns, paso 25ns. La secuencia de valores debe ser 50ns,75ns. Ahora está midiendo para 50ns,75ns y 100ns, donde este último está fuera del rango dado por el usuario.

(versión 1.2.4)

**Comment by jsbarbosa** [comment]
Resuelto en versión 1.2.5
