### ISSUE TITLE
barrido: tiempo inicial de espera insuficiente

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#41]
En los barridos, tanto de retraso como de dormido, el primer dato leido está siendo siempre 0. Esto se puede corregir con la lectura del registro _dataID_, y/o con la lectura del registro _timeLeft_ para garantizar que el dato leído sea válido y nuevo.

Ejemplo: tengo un sistema con 100 conteos en A, 10000 conteos en B, 100 coincidencias para retraso 0.
Adquiriendo 1 solo dato por retraso, obtengo lo siguiente:
![delaysweep abacus1 2 4 test01](https://user-images.githubusercontent.com/14864395/40932329-96b177a0-67f3-11e8-8732-7ac77d94f02b.png)

Si se repite el experimento adquiriendo 4 datos por retraso, se obtiene lo siguiente:
![delaysweep abacus1 2 4 test02](https://user-images.githubusercontent.com/14864395/40932383-c8c69482-67f3-11e8-8db4-fd867b50ebf3.png)
donde el pico se encuentra en 75 coincidencias. El real es 100, pero al haber leido en las 4 lecturas 0 (incorrecto), 100, 100 y 100, su promedio da 75.

(versión 1.2.4)

**Comment by jsbarbosa** [comment]
Corregido en version 1.2.5 y pyAbacus 1.0.5
