### ISSUE TITLE
barrido retraso: incluir 'coincidence window'

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#42]
En la ventana de barrido de retrasos, actualmente aparece el parámetro _sampling time_, el cual no se puede editar (correcto).
Incluir de forma similar el parámetro _coincidence window_, pues es relevante al momento de hacer un barrido por retrasos de las coincidencias.
(versión 1.2.4)

**Comment by jsbarbosa** [comment]
Incluido en la versión 1.2.5
