### ISSUE TITLE
Mostrar los últimos N datos

### ISSUE THREAD

**Issue by jsbarbosa** [Tausand-dev/AbacusSoftware#48]
En la gráfica y tabla, dejar al usuario que escoja que muestre los últimos N datos, siendo N dado por el usuario.

**Comment by daguzman35** [comment]
Respaldada esta solicitud de nueva funcionalidad por un usuario (cliente):

> "I have seen that the plot in the user interface is an accumulation of all the data from the beginning. If this plot is in the format of running screen it will be very useful in general from many aspect."

**Comment by daguzman35** [comment]
implementado en versión 1.5.0, en noviembre de 2021
