### ISSUE TITLE
Error punto

### ISSUE THREAD

**Issue by JoanAmaya** [Tausand-dev/AbacusSoftware#76]
El software tienen un error al agregar un punto en la ruta

**Comment by daguzman35** [comment]
(versión 1.6.0)

**Comment by daguzman35** [comment]
(v1.6.1) Al crear una ruta de carpeta o nombre de archivo que incluya puntos, software elimina por defecto los puntos. Por esto no encuentra las rutas.

![Image](https://github.com/orgs/Tausand-dev/projects/2/assets/14864395/98bf26c5-0bc8-476e-8caf-ad378a1c48c4)

En este ejemplo, no puede acceder a la carpeta con ruta
    `C:\Users\Tausand\Documents\datos.prueba.abacus`
la cual sí existe

![Image](https://github.com/orgs/Tausand-dev/projects/2/assets/14864395/2f0952e3-c981-4cb7-a594-ca7216892f70)

**Comment by JoanAmaya** [comment]
El error se produce en la función que checkFileName que busca la extensión del archivo y para ello reconstruye la ruta ignorando puntos anteriores lo que ocasiona, que se cree una nueva ruta sin puntos que el sistema no va a poder localizar a menos de que exista, el error es diferente al reportado anteriormente ya que el anterior se producía por un desempaquetamiento de un string que esperaba 2 argumentos, el error se soluciona y se sube en la rama UpdateAbacus1.6.1, una vez se revise nuevamente se solucionara con los instaladores.

**Comment by daguzman35** [comment]
(v1.6.1 en desarrollo). Probado, ejecutando 'test.py' de rama 'UpdateAbacus1.6.1'. Funciona correctamente; el mensaje de error reportado ya no aparece. Almacena en carpetas y/o archivos con puntos en su ruta.


![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/2bb0e98d-7f6a-4106-a8c8-2109ab12ee34)

Favor generar instalador.
