### ISSUE TITLE
Abacus Software (Linux): Botón 'open' genera cierre de software

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#84]
(v1.6.1 del 7 de junio de 2024)
En Linux, Ubuntu 22.04, se puede ejecutar el software compilado (ok). Al hacer clic en botón 'open' para cambiar la ruta donde se guardan los archivos, el software se cierra. El último error que sale en terminal dice:

> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Humanity/status/16/image-missing.svg: No se ha podido cargar el módulo de carga de imágenes: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: pango_attr_overline_new (gdk-pixbuf-error-quark, 5)

Todo lo que apareció registrado en la terminal durante la ejecución del software fue:

> david@ubuntu-Lenovo-IdeaPad:~/Escritorio$ ./AbacusSoftware.AppImage 
> libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: radeonsi
> libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: radeonsi
> libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
> libGL error: failed to load driver: swrast
> /home/david/Tausand
> 1000
> 1000
> 1
> 1000
> 1000
> 1000
> 1000
> 
> (AbacusSoftware:20049): Gtk-WARNING **: 15:31:48.238: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> **
> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Humanity/status/16/image-missing.svg: No se ha podido cargar el módulo de carga de imágenes: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: pango_attr_overline_new (gdk-pixbuf-error-quark, 5)
> Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Humanity/status/16/image-missing.svg: No se ha podido cargar el módulo de carga de imágenes: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: pango_attr_overline_new (gdk-pixbuf-error-quark, 5)
> Abortado (`core' generado)

**Comment by JoanAmaya** [comment]
Fuente del error: Se encuentra que el error proviene de la diferencia entre versiones de Ubuntu, en la versión 20.04 y 20.01 no ocurre, revisaré que se puede hacer para solucionarlo.

**Comment by daguzman35** [comment]
Usando AbacusSoftware22.AppImage generado el 20 de junio, ha quedado solucionado para Ubuntu versión 22.04. Ok.

Si ejecuto el compilado para 20.04 mientras uso 22.04, el error reportado aparece.

Si intento ejecutar el compilado para 23.10-24.04, el programa no ejecuta, tal como se espera (ok).
