### ISSUE TITLE
botones save bloqueados tras start y finalización de rutinas (delay sweep, sleep sweep, g2)

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#90]
(1.7.0) Funcionalidad g2. Cuando se da un 'start' de la medida, y se espera que se complete, el sistema bloquea los botones 'save' y 'save plots', lo cual impide que se almacenen los datos de g2.

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/af65b686-df54-4bff-a2f4-70e402d4db3c)

Si se hace un 'stop', los botones 'save' y 'save plots' sí quedan habilitados (correcto).

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/60e85735-c662-410a-b3f8-9c2f06ed8e57)

**Comment by daguzman35** [comment]
(1.7.0) Esto también pasa en _delay sweep_ y en _sleep sweep_ (bloquea botones 'save' y 'save plots' al terminar barrido):


![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/e8e0c171-fc00-46b1-bc11-617e47174b1f)

y



![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/25b056ed-0d16-4d5e-a9a2-a42722536f5c)

**Comment by JoanAmaya** [comment]
Se soluciona que los botones no se habilitan cuando se completan las mediciones
