### ISSUE TITLE
g2: revisar cálculo

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#91]
(1.7.0) El valor estimado de g2 anteriores va cambiando a medida que cambia el retraso. Ejemplo, sistema calcula g2(tau=0)=2.1, luego cuando calcula g2(tau=2ns)=1.5 el sistema también modifica el valor de g2(tau=0) a 1.5, el cual no debería ser modificado en memoria.

Ejemplo, g2(tau=2ns)=6.7

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/7bbf6a7e-f4be-4fde-9f67-f456e110f0e7)

luego sigue y encuentra g2(tau=6ns)=1.68 ... pero borra g2(tau=2ns) que lo deja como 1.68.

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/dee43089-c91a-4467-adb3-0e427b83c5fa)

luego sigue y encuentra g2(tau=10ns)=0.6 ... y borra todos los g2 anteriores, como g2(tau=2ns) y g2(tau=6ns).

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/004e5744-2aae-41c5-9919-ac9ffabe8c2b)

**Comment by JoanAmaya** [comment]
Se corrige el calculo de la g2
