### ISSUE TITLE
archivo datos, header accidentales, repetido

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#92]
(1.7.0) En archivo de datos creado cuando se ha habilitado la estimación de coincidencias accidentales, se encuentra que los encabezados asociados a las accidentales quedan repetidos varias veces. Esto parece sucede cuando se habilita, se deshabilita y se vuelve a habilitar la opción de accidentales; en el archivo de datos se crea de nuevo el encabezado.

Ejemplo, donde han quedado 3 veces creados los encabezados de accidentales:

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/c27c09c7-f66e-4a9a-91c9-0c46b502f030)

las filas de datos quedan correctas

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/ec930471-1f2f-4e0a-bb75-0783f03dff08)

**Comment by JoanAmaya** [comment]
Se corrige el error de header repetido, el header queda constante para todos los guardados
