### ISSUE TITLE
datos no aparecen en interfaz

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#93]
(1.7.0 del 4 de julio de 2024)
Probado con AB2504 y pulsos reales de generador de señales. Pulsos usados: 
canal A=1MHz
canal B=1MHz

Interfaz no muestra ningún dato tomado del dispositivo. No muestra puntos en gráficas. No muestra valores en 'current'. Al revisar valores guardados en archivos de datos, los datos sí son guardados correctamente.

Interfaz:

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/31254a15-d69b-4b09-9890-8d357e24a2bd)

no hay ningún 'plot' pintado
no muestra datos en tabla 'historical'
los valores en ventanas 'current' son todos cero

Al ver archivo de datos asociado:

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/b13aaf64-d539-4f75-a1f2-12cc90874de1)

se ven los pulsos almacenados de entradas A y C correctamente, al igual que las coincidencias AC: 1MHz.

**Comment by JoanAmaya** [comment]
El error se produce por la resolución del equipo ya que se estaba tomando de acuerdo al nombre de este mismo. Ahora la resolución se toma a partir de la función de pyAbacus de getResolution() por lo tanto no debería haber ningún problema relacionado al nombre, en dado caso que sirva la solución cerrar el issue
