### ISSUE TITLE
g2: coincidence window debe ser resolución equipo

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#94]
(v1.7.0 del 4 de julio de 2024)
Probado con AB2504.

Al abrir funcionalidad 'g2 function', el valor de ventana de coincidencias para esta prueba debería asignarse en la resolución del equipo. En el caso de AB2504, su resolución es de 2ns. La funcionalidad 'g2 function' lo está aplicando como 10ns, que es el valor asignado en el equipo antes de entrar a esta funcionalidad.

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/56a63d85-ca0c-4fe5-9838-8d6b03ddf2bd)

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/de6b3576-ad0c-487d-8da1-69420eaf1921)

**Comment by daguzman35** [comment]
Usar `getResolution()` o `getResolutionByName()` de librería PyAbacus.

**Comment by JoanAmaya** [comment]
Se arregla el problema, el programa capta la resolución del equipo antes de hacer el open de la conexión para evitar errores debido al acceso del puerto
