### ISSUE TITLE
g2: eje horizontal es delay time tau

### ISSUE THREAD

**Issue by daguzman35** [Tausand-dev/AbacusSoftware#95]
(v1.7.0 del 4 de julio de 2024)
En gráfica de g2, el eje horizontal debe ser retraso, '_delay time_', o en su defecto '_tau_'.
Actualmente dice '_coincidence time_': incorrecto.

![Image](https://github.com/Tausand-dev/AbacusSoftware/assets/14864395/08c38be3-6215-46ad-b792-7b4ca239e3ca)

**Comment by JoanAmaya** [comment]
Se corrige el error cambiando el label a Delay Time
